apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVFJ6MUNHaDJnYk13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeE1EUXhNREl5TURKYUZ3MHpOakF4TURJeE1ESTNNREphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURMNVBwU1JrSjNhT2VxTmozNzNPZFp3cEFJcm42S2dWa1d4ci9nbnIxYnNyQ1pRbUNzRGFHUWZmT0gKRlhFYjNRYW9hZldyQVRaWWU5ZkZkWGkxZ2JqdmhJbjlQeEMrQVFpNWZqTDVKTENIbXMrYUdQK1ZSa0xDU05KVgpBNWNEMXNCc1Bvc0JIK3Q1T3kvZjRlK0lLUm83VUNYNUozVGI3WnkxUmRKclZFM0lsN25QcFJSTFNvRFFkaWJRCjJacEU2bXo4Wm14QW1XMndtVHhoUEx4Y2ZMYVUvZlJMbWpOYkxhVUVvVnNacHpielFiQnlQb2lqc3c5dk0rS1UKdkJaZGMrTnBUMXMxcHovdEw3U1FYcUF0ZVFqbEFJcjg2MFpxcktocGRHSzNYMmhJLzNpSFpJTmNOVGJmclBiVgpCa05aTXV3eEtOV0Vjd1pJZG9uOE1WUERYamZEQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWjYyTGJIMW9YL3BXczFxTXI0ZWw2ZXYyYVZUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQzBoeVUyYlNzMAp1cnpFOXd3K3ZtTXdKZ0RkTnlnOWlrdjB5bVpoWEhtdGQrL05lM1phNDdyblcvTS9YVlpXSVBydEF0Y21DMjgyCkxXTnlvRElzZGhqcXJIak01ZnRIZTlWREpCbXRxWERIeGY1N1liNzJ3TGhicS9FQ2NlNWdrNGRvRFRaTEJnZ2cKQzcyZWwzdXlyeFdWbmFtWVFjbDBuMnJnNVRuZW1wNzhkamZ2Y0ZibVVrajUrUW9tSEs3SWN2cjJDNktoTEZTWAo1cGhYbjAvYkFWME5KR0dIcWRKTXlMa0ZsaXAwM1U2Rjl5UWhUWVh0b2RIZGVmTGZaWW83QkpJaGVDbXJSanZVClBCRjIyWmR5T1NuZ1FURnZtOGt2eUJQdWlxM2tnb08wQVJaSTZaT2lxQ3ZtL3liZDYzMTFiVytodi9ROU5SUjQKcDcwanFuME9DOVp1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://172.18.0.2:6443
  name: my-kind
contexts:
- context:
    cluster: my-kind
    user: system:node:my-kind-control-plane
  name: system:node:my-kind-control-plane@my-kind
current-context: system:node:my-kind-control-plane@my-kind
kind: Config
users:
- name: system:node:my-kind-control-plane
  user:
    client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
    client-key: /var/lib/kubelet/pki/kubelet-client-current.pem